
export default function Home() {
  return (
  <div className="container">
    <head>
      <title>Catastro</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </head>
    <body>
      <header>
        <div class="logo">
          <p>CATASTRO</p>
        </div>
      </header>
      <main>
        <div class="titleWrapper">
          <p>Predios</p>
          <button class="button-outline">+</button>
        </div>
        <div class="contentWrapper">
          <div class="prediosWrapper">
            
          </div>
        </div>
      </main>
      <footer>
        <p>Creado por David González</p>
      </footer>
    </body>
    
  </div>
  );
};